
CREATE TABLE DIRECTOR1 (
DIR_ID varchar(20),
DIR_NAME VARCHAR (20),
DIR_PHONE varchar(20), 
PRIMARY KEY (DIR_ID));

CREATE TABLE MOVIES3 ( 
MOV_ID varchar(20),
MOV_TITLE VARCHAR (25),
MOV_YEAR varchar(20),
MOV_LANG VARCHAR (12),
DIR_ID varchar(20), 
PRIMARY KEY (MOV_ID),
FOREIGN KEY (DIR_ID) REFERENCES DIRECTOR (DIR_ID));

CREATE TABLE MOVIE_CAST3 ( 
ACT_ID varchar(20),
MOV_ID varchar(20),
ROLE VARCHAR (10),
PRIMARY KEY (ACT_ID, MOV_ID),
FOREIGN KEY (ACT_ID) REFERENCES ACTOR (ACT_ID), 
FOREIGN KEY (MOV_ID) REFERENCES MOVIES (MOV_ID));

CREATE TABLE RATING4 ( 
MOV_ID varchar(20),
REV_STARS VARCHAR (25), 
PRIMARY KEY (MOV_ID),
FOREIGN KEY (MOV_ID) REFERENCES MOVIES (MOV_ID));
